### ISSUE TITLE
Create v.3x branch for deploy to libappstest

### ISSUE THREAD

**Issue by crowesn** [uclibs/omeka-s#1]
1. - [x] Commit and push existing v.2 changes from libappstest to repo (Sean)
2. - [x] Create backup of v.2 omeka-s and data for restoration in case of backout (Azeez & Sean)
3. - [x] Create new branch for Omeka v.3 with update source files **We need to retain config, logs, modules, and themes directories. (Lisa & Sean)
4. - [ ] On new instance, make module and theme upgrades for v.3 (Lisa)
5. - [ ] Install easyInstall Module [https://omeka.org/s/modules/EasyInstall/](https://omeka.org/s/modules/EasyInstall/)
5. - [x] Notify users of upgrade.
5. - [ ] Verify that everything on v.3 is working, check existing collections
6. - [ ] Notify users of migration and redirect to new site or disable v.2 
6. - [ ] Push module and theme changes to github 
7. - [ ] Merge v.3 changes to qa branch 
8. - [ ] Delete old v.2 site

**Comment by hortongn** [comment]
@crowesn can this issue be closed?
