### ISSUE TITLE
QA Omeka instance broken

### ISSUE THREAD

**Issue by hortongn** [uclibs/omeka-s#16]
https://libappstest.libraries.uc.edu/sites/ is showing **Omeka S encountered an error**

**Comment by haitzlm** [comment]
This appears to be working now?

**Comment by hortongn** [comment]
Interesting.  Still broken for me, but works fine in a private browser window.  I must have a weird cookie or something I need to clear after we changed the path or something.  I'll close this for now and troubleshoot locally.
